// Auto-generated by scripts/prepare-category-assets.mjs — do not edit manually
export type GeneratedCategoryGallery = {
  slug: string;
  title: string;
  coverImage: string;
  galleryImages: string[];
};

export const CATEGORY_GALLERIES: GeneratedCategoryGallery[] = [
  {
    "slug": "garments-showroom-design",
    "title": "Garments Showroom Design",
    "coverImage": "/assets/categories/garments-showroom-design/garments-showroom-design-01.jpg",
    "galleryImages": [
      "/assets/categories/garments-showroom-design/garments-showroom-design-01.jpg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-02.jpg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-03.jpg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-04.jpg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-05.jpg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-06.jpg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-07.jpg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-08.jpg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-09.jpg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-10.jpg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-11.jpg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-12.jpg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-13.jpg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-14.jpg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-15.jpg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-16.jpg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-17.jpg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-18.jpg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-19.jpg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-20.jpg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-21.jpg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-22.jpg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-23.jpeg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-24.jpeg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-25.jpeg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-26.jpeg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-27.jpeg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-28.jpeg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-29.jpeg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-30.jpeg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-31.jpeg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-32.jpeg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-33.jpeg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-34.jpeg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-35.jpeg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-36.jpeg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-37.jpeg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-38.jpeg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-39.jpeg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-40.jpeg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-41.jpeg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-42.jpeg",
      "/assets/categories/garments-showroom-design/garments-showroom-design-43.jpeg"
    ]
  },
  {
    "slug": "jewellery-showroom-design",
    "title": "Jewellery Showroom Design",
    "coverImage": "/assets/categories/jewellery-showroom-design/jewellery-showroom-design-01.jpg",
    "galleryImages": [
      "/assets/categories/jewellery-showroom-design/jewellery-showroom-design-01.jpg",
      "/assets/categories/jewellery-showroom-design/jewellery-showroom-design-02.jpg",
      "/assets/categories/jewellery-showroom-design/jewellery-showroom-design-03.jpg",
      "/assets/categories/jewellery-showroom-design/jewellery-showroom-design-04.jpg",
      "/assets/categories/jewellery-showroom-design/jewellery-showroom-design-05.jpg",
      "/assets/categories/jewellery-showroom-design/jewellery-showroom-design-06.jpg",
      "/assets/categories/jewellery-showroom-design/jewellery-showroom-design-07.jpg",
      "/assets/categories/jewellery-showroom-design/jewellery-showroom-design-08.jpg",
      "/assets/categories/jewellery-showroom-design/jewellery-showroom-design-09.jpg"
    ]
  },
  {
    "slug": "shoe-showroom-design",
    "title": "Shoe Showroom Design",
    "coverImage": "/assets/categories/shoe-showroom-design/shoe-showroom-design-01.jpg",
    "galleryImages": [
      "/assets/categories/shoe-showroom-design/shoe-showroom-design-01.jpg",
      "/assets/categories/shoe-showroom-design/shoe-showroom-design-02.jpg",
      "/assets/categories/shoe-showroom-design/shoe-showroom-design-03.jpg",
      "/assets/categories/shoe-showroom-design/shoe-showroom-design-04.jpg",
      "/assets/categories/shoe-showroom-design/shoe-showroom-design-05.jpg",
      "/assets/categories/shoe-showroom-design/shoe-showroom-design-06.jpg",
      "/assets/categories/shoe-showroom-design/shoe-showroom-design-07.jpg",
      "/assets/categories/shoe-showroom-design/shoe-showroom-design-08.jpg",
      "/assets/categories/shoe-showroom-design/shoe-showroom-design-09.jpg",
      "/assets/categories/shoe-showroom-design/shoe-showroom-design-10.jpg",
      "/assets/categories/shoe-showroom-design/shoe-showroom-design-11.jpg",
      "/assets/categories/shoe-showroom-design/shoe-showroom-design-12.jpg"
    ]
  },
  {
    "slug": "mobile-showroom-design",
    "title": "Mobile Showroom Design",
    "coverImage": "/assets/categories/mobile-showroom-design/mobile-showroom-design-01.jpg",
    "galleryImages": [
      "/assets/categories/mobile-showroom-design/mobile-showroom-design-01.jpg",
      "/assets/categories/mobile-showroom-design/mobile-showroom-design-02.jpg",
      "/assets/categories/mobile-showroom-design/mobile-showroom-design-03.jpg",
      "/assets/categories/mobile-showroom-design/mobile-showroom-design-04.jpg",
      "/assets/categories/mobile-showroom-design/mobile-showroom-design-05.jpg"
    ]
  },
  {
    "slug": "supermarket-design",
    "title": "Supermarket Design",
    "coverImage": "/assets/categories/supermarket-design/supermarket-design-01.jpg",
    "galleryImages": [
      "/assets/categories/supermarket-design/supermarket-design-01.jpg",
      "/assets/categories/supermarket-design/supermarket-design-02.jpg",
      "/assets/categories/supermarket-design/supermarket-design-03.jpg",
      "/assets/categories/supermarket-design/supermarket-design-04.jpg",
      "/assets/categories/supermarket-design/supermarket-design-05.jpg",
      "/assets/categories/supermarket-design/supermarket-design-06.jpg",
      "/assets/categories/supermarket-design/supermarket-design-07.jpg",
      "/assets/categories/supermarket-design/supermarket-design-08.jpg",
      "/assets/categories/supermarket-design/supermarket-design-09.jpg",
      "/assets/categories/supermarket-design/supermarket-design-10.jpg",
      "/assets/categories/supermarket-design/supermarket-design-11.jpg",
      "/assets/categories/supermarket-design/supermarket-design-12.jpg",
      "/assets/categories/supermarket-design/supermarket-design-13.jpg",
      "/assets/categories/supermarket-design/supermarket-design-14.jpg"
    ]
  },
  {
    "slug": "gift-showroom-design",
    "title": "Gift & Toy Showroom Design",
    "coverImage": "/assets/categories/gift-showroom-design/gift-showroom-design-01.jpg",
    "galleryImages": [
      "/assets/categories/gift-showroom-design/gift-showroom-design-01.jpg",
      "/assets/categories/gift-showroom-design/gift-showroom-design-02.jpg",
      "/assets/categories/gift-showroom-design/gift-showroom-design-03.jpg",
      "/assets/categories/gift-showroom-design/gift-showroom-design-04.jpg",
      "/assets/categories/gift-showroom-design/gift-showroom-design-05.jpg",
      "/assets/categories/gift-showroom-design/gift-showroom-design-06.jpg",
      "/assets/categories/gift-showroom-design/gift-showroom-design-07.jpg",
      "/assets/categories/gift-showroom-design/gift-showroom-design-08.jpg",
      "/assets/categories/gift-showroom-design/gift-showroom-design-09.jpg",
      "/assets/categories/gift-showroom-design/gift-showroom-design-10.jpg",
      "/assets/categories/gift-showroom-design/gift-showroom-design-11.jpg",
      "/assets/categories/gift-showroom-design/gift-showroom-design-12.jpg",
      "/assets/categories/gift-showroom-design/gift-showroom-design-13.jpg",
      "/assets/categories/gift-showroom-design/gift-showroom-design-14.jpg"
    ]
  },
  {
    "slug": "medical-store-design",
    "title": "Medical Store Design",
    "coverImage": "/assets/categories/medical-store-design/medical-store-design-01.jpg",
    "galleryImages": [
      "/assets/categories/medical-store-design/medical-store-design-01.jpg",
      "/assets/categories/medical-store-design/medical-store-design-02.jpg",
      "/assets/categories/medical-store-design/medical-store-design-03.jpg",
      "/assets/categories/medical-store-design/medical-store-design-04.jpg",
      "/assets/categories/medical-store-design/medical-store-design-05.jpg",
      "/assets/categories/medical-store-design/medical-store-design-06.jpg",
      "/assets/categories/medical-store-design/medical-store-design-07.jpg"
    ]
  },
  {
    "slug": "watch-showroom-design",
    "title": "Watch Showroom Design",
    "coverImage": "/assets/categories/watch-showroom-design/watch-showroom-design-01.jpg",
    "galleryImages": [
      "/assets/categories/watch-showroom-design/watch-showroom-design-01.jpg",
      "/assets/categories/watch-showroom-design/watch-showroom-design-02.jpg",
      "/assets/categories/watch-showroom-design/watch-showroom-design-03.jpg",
      "/assets/categories/watch-showroom-design/watch-showroom-design-04.jpg",
      "/assets/categories/watch-showroom-design/watch-showroom-design-05.jpg",
      "/assets/categories/watch-showroom-design/watch-showroom-design-06.jpg"
    ]
  }
];

export function getCategoryGallery(slug: string): GeneratedCategoryGallery | undefined {
  return CATEGORY_GALLERIES.find((c) => c.slug === slug);
}
