// Auto-generated by scripts/prepare-optical-assets.mjs — do not edit manually
export type GeneratedOpticalProject = {
  slug: string;
  title: string;
  location: string;
  coverImage: string;
  galleryImages: string[];
  galleryVideos: string[];
};

export const OPTICAL_PROJECTS: GeneratedOpticalProject[] = [
  {
    "slug": "avon-optical-kanpur",
    "title": "Avon Optical",
    "location": "Kanpur, Uttar Pradesh",
    "coverImage": "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-01.png",
    "galleryImages": [
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-01.png",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-02.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-03.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-04.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-05.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-06.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-07.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-08.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-09.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-10.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-11.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-12.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-13.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-14.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-15.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-16.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-17.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-18.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-19.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-20.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-21.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-22.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-23.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-24.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-25.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-26.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-27.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-28.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-29.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-30.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-31.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-32.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-33.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-34.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-35.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-36.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-37.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-38.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-39.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-40.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-41.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-42.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-43.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-44.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-45.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-46.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-47.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-48.jpeg",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-49.jpeg"
    ],
    "galleryVideos": [
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-video-01.mp4",
      "/assets/projects/avon-optical-kanpur/avon-optical-kanpur-video-02.mp4"
    ]
  },
  {
    "slug": "eye-class-optical-boutique-hyderabad",
    "title": "Eye Class Optical Boutique",
    "location": "Hyderabad, Telangana",
    "coverImage": "/assets/projects/eye-class-optical-boutique-hyderabad/eye-class-optical-boutique-hyderabad-01.jpeg",
    "galleryImages": [
      "/assets/projects/eye-class-optical-boutique-hyderabad/eye-class-optical-boutique-hyderabad-01.jpeg",
      "/assets/projects/eye-class-optical-boutique-hyderabad/eye-class-optical-boutique-hyderabad-02.jpeg",
      "/assets/projects/eye-class-optical-boutique-hyderabad/eye-class-optical-boutique-hyderabad-03.jpeg",
      "/assets/projects/eye-class-optical-boutique-hyderabad/eye-class-optical-boutique-hyderabad-04.jpeg",
      "/assets/projects/eye-class-optical-boutique-hyderabad/eye-class-optical-boutique-hyderabad-05.jpeg",
      "/assets/projects/eye-class-optical-boutique-hyderabad/eye-class-optical-boutique-hyderabad-06.jpeg",
      "/assets/projects/eye-class-optical-boutique-hyderabad/eye-class-optical-boutique-hyderabad-07.jpeg",
      "/assets/projects/eye-class-optical-boutique-hyderabad/eye-class-optical-boutique-hyderabad-08.jpeg",
      "/assets/projects/eye-class-optical-boutique-hyderabad/eye-class-optical-boutique-hyderabad-09.jpeg",
      "/assets/projects/eye-class-optical-boutique-hyderabad/eye-class-optical-boutique-hyderabad-10.jpeg",
      "/assets/projects/eye-class-optical-boutique-hyderabad/eye-class-optical-boutique-hyderabad-11.jpeg",
      "/assets/projects/eye-class-optical-boutique-hyderabad/eye-class-optical-boutique-hyderabad-12.jpeg",
      "/assets/projects/eye-class-optical-boutique-hyderabad/eye-class-optical-boutique-hyderabad-13.jpeg",
      "/assets/projects/eye-class-optical-boutique-hyderabad/eye-class-optical-boutique-hyderabad-14.jpeg"
    ],
    "galleryVideos": []
  },
  {
    "slug": "house-of-okkio-noida",
    "title": "House of Okkio",
    "location": "Noida, Uttar Pradesh",
    "coverImage": "/assets/projects/house-of-okkio-noida/house-of-okkio-noida-01.jpeg",
    "galleryImages": [
      "/assets/projects/house-of-okkio-noida/house-of-okkio-noida-01.jpeg",
      "/assets/projects/house-of-okkio-noida/house-of-okkio-noida-02.jpeg",
      "/assets/projects/house-of-okkio-noida/house-of-okkio-noida-03.jpeg",
      "/assets/projects/house-of-okkio-noida/house-of-okkio-noida-04.jpeg",
      "/assets/projects/house-of-okkio-noida/house-of-okkio-noida-05.jpeg",
      "/assets/projects/house-of-okkio-noida/house-of-okkio-noida-06.jpeg",
      "/assets/projects/house-of-okkio-noida/house-of-okkio-noida-07.jpeg",
      "/assets/projects/house-of-okkio-noida/house-of-okkio-noida-08.jpeg",
      "/assets/projects/house-of-okkio-noida/house-of-okkio-noida-09.jpeg",
      "/assets/projects/house-of-okkio-noida/house-of-okkio-noida-10.jpeg",
      "/assets/projects/house-of-okkio-noida/house-of-okkio-noida-11.jpeg",
      "/assets/projects/house-of-okkio-noida/house-of-okkio-noida-12.jpeg",
      "/assets/projects/house-of-okkio-noida/house-of-okkio-noida-13.jpeg",
      "/assets/projects/house-of-okkio-noida/house-of-okkio-noida-14.jpeg",
      "/assets/projects/house-of-okkio-noida/house-of-okkio-noida-15.jpeg",
      "/assets/projects/house-of-okkio-noida/house-of-okkio-noida-16.jpeg",
      "/assets/projects/house-of-okkio-noida/house-of-okkio-noida-17.jpeg",
      "/assets/projects/house-of-okkio-noida/house-of-okkio-noida-18.jpeg",
      "/assets/projects/house-of-okkio-noida/house-of-okkio-noida-19.jpeg",
      "/assets/projects/house-of-okkio-noida/house-of-okkio-noida-20.jpeg",
      "/assets/projects/house-of-okkio-noida/house-of-okkio-noida-21.jpeg",
      "/assets/projects/house-of-okkio-noida/house-of-okkio-noida-22.jpeg"
    ],
    "galleryVideos": [
      "/assets/projects/house-of-okkio-noida/house-of-okkio-noida-video-01.mp4"
    ]
  },
  {
    "slug": "meta-vision-dharamshala",
    "title": "Meta Vision",
    "location": "Dharamshala, Himachal Pradesh",
    "coverImage": "/assets/projects/meta-vision-dharamshala/meta-vision-dharamshala-01.jpg",
    "galleryImages": [
      "/assets/projects/meta-vision-dharamshala/meta-vision-dharamshala-01.jpg",
      "/assets/projects/meta-vision-dharamshala/meta-vision-dharamshala-02.jpg",
      "/assets/projects/meta-vision-dharamshala/meta-vision-dharamshala-03.jpg",
      "/assets/projects/meta-vision-dharamshala/meta-vision-dharamshala-04.jpg",
      "/assets/projects/meta-vision-dharamshala/meta-vision-dharamshala-05.jpg",
      "/assets/projects/meta-vision-dharamshala/meta-vision-dharamshala-06.jpg",
      "/assets/projects/meta-vision-dharamshala/meta-vision-dharamshala-07.jpg",
      "/assets/projects/meta-vision-dharamshala/meta-vision-dharamshala-08.jpg",
      "/assets/projects/meta-vision-dharamshala/meta-vision-dharamshala-09.jpg",
      "/assets/projects/meta-vision-dharamshala/meta-vision-dharamshala-10.jpeg",
      "/assets/projects/meta-vision-dharamshala/meta-vision-dharamshala-11.jpeg",
      "/assets/projects/meta-vision-dharamshala/meta-vision-dharamshala-12.jpeg",
      "/assets/projects/meta-vision-dharamshala/meta-vision-dharamshala-13.jpeg",
      "/assets/projects/meta-vision-dharamshala/meta-vision-dharamshala-14.jpeg",
      "/assets/projects/meta-vision-dharamshala/meta-vision-dharamshala-15.jpeg",
      "/assets/projects/meta-vision-dharamshala/meta-vision-dharamshala-16.jpeg",
      "/assets/projects/meta-vision-dharamshala/meta-vision-dharamshala-17.jpeg",
      "/assets/projects/meta-vision-dharamshala/meta-vision-dharamshala-18.jpeg",
      "/assets/projects/meta-vision-dharamshala/meta-vision-dharamshala-19.jpeg",
      "/assets/projects/meta-vision-dharamshala/meta-vision-dharamshala-20.png"
    ],
    "galleryVideos": [
      "/assets/projects/meta-vision-dharamshala/meta-vision-dharamshala-video-01.mp4"
    ]
  },
  {
    "slug": "nagpal-opticians-rudarpur",
    "title": "Nagpal Opticians",
    "location": "Rudarpur, Uttarakhand",
    "coverImage": "/assets/projects/nagpal-opticians-rudarpur/nagpal-opticians-rudarpur-01.png",
    "galleryImages": [
      "/assets/projects/nagpal-opticians-rudarpur/nagpal-opticians-rudarpur-01.png",
      "/assets/projects/nagpal-opticians-rudarpur/nagpal-opticians-rudarpur-02.jpeg",
      "/assets/projects/nagpal-opticians-rudarpur/nagpal-opticians-rudarpur-03.jpeg",
      "/assets/projects/nagpal-opticians-rudarpur/nagpal-opticians-rudarpur-04.jpeg",
      "/assets/projects/nagpal-opticians-rudarpur/nagpal-opticians-rudarpur-05.jpeg",
      "/assets/projects/nagpal-opticians-rudarpur/nagpal-opticians-rudarpur-06.jpeg",
      "/assets/projects/nagpal-opticians-rudarpur/nagpal-opticians-rudarpur-07.jpeg",
      "/assets/projects/nagpal-opticians-rudarpur/nagpal-opticians-rudarpur-08.jpeg",
      "/assets/projects/nagpal-opticians-rudarpur/nagpal-opticians-rudarpur-09.jpeg",
      "/assets/projects/nagpal-opticians-rudarpur/nagpal-opticians-rudarpur-10.jpeg",
      "/assets/projects/nagpal-opticians-rudarpur/nagpal-opticians-rudarpur-11.jpeg",
      "/assets/projects/nagpal-opticians-rudarpur/nagpal-opticians-rudarpur-12.jpeg",
      "/assets/projects/nagpal-opticians-rudarpur/nagpal-opticians-rudarpur-13.jpeg",
      "/assets/projects/nagpal-opticians-rudarpur/nagpal-opticians-rudarpur-14.jpeg",
      "/assets/projects/nagpal-opticians-rudarpur/nagpal-opticians-rudarpur-15.jpeg"
    ],
    "galleryVideos": []
  },
  {
    "slug": "nethra-opticals-visakhapatnam",
    "title": "Nethra Opticals",
    "location": "Visakhapatnam, Andhra Pradesh",
    "coverImage": "/assets/projects/nethra-opticals-visakhapatnam/nethra-opticals-visakhapatnam-01.jpeg",
    "galleryImages": [
      "/assets/projects/nethra-opticals-visakhapatnam/nethra-opticals-visakhapatnam-01.jpeg",
      "/assets/projects/nethra-opticals-visakhapatnam/nethra-opticals-visakhapatnam-02.jpeg",
      "/assets/projects/nethra-opticals-visakhapatnam/nethra-opticals-visakhapatnam-03.jpeg",
      "/assets/projects/nethra-opticals-visakhapatnam/nethra-opticals-visakhapatnam-04.jpeg",
      "/assets/projects/nethra-opticals-visakhapatnam/nethra-opticals-visakhapatnam-05.jpeg",
      "/assets/projects/nethra-opticals-visakhapatnam/nethra-opticals-visakhapatnam-06.jpeg",
      "/assets/projects/nethra-opticals-visakhapatnam/nethra-opticals-visakhapatnam-07.jpeg",
      "/assets/projects/nethra-opticals-visakhapatnam/nethra-opticals-visakhapatnam-08.jpeg",
      "/assets/projects/nethra-opticals-visakhapatnam/nethra-opticals-visakhapatnam-09.jpeg",
      "/assets/projects/nethra-opticals-visakhapatnam/nethra-opticals-visakhapatnam-10.jpeg",
      "/assets/projects/nethra-opticals-visakhapatnam/nethra-opticals-visakhapatnam-11.jpeg",
      "/assets/projects/nethra-opticals-visakhapatnam/nethra-opticals-visakhapatnam-12.jpeg"
    ],
    "galleryVideos": [
      "/assets/projects/nethra-opticals-visakhapatnam/nethra-opticals-visakhapatnam-video-01.mp4"
    ]
  },
  {
    "slug": "optical-world-bangalore",
    "title": "Optical World",
    "location": "Bangalore, Karnataka",
    "coverImage": "/assets/projects/optical-world-bangalore/optical-world-bangalore-01.jpeg",
    "galleryImages": [
      "/assets/projects/optical-world-bangalore/optical-world-bangalore-01.jpeg",
      "/assets/projects/optical-world-bangalore/optical-world-bangalore-02.jpeg",
      "/assets/projects/optical-world-bangalore/optical-world-bangalore-03.jpeg",
      "/assets/projects/optical-world-bangalore/optical-world-bangalore-04.jpeg",
      "/assets/projects/optical-world-bangalore/optical-world-bangalore-05.jpeg",
      "/assets/projects/optical-world-bangalore/optical-world-bangalore-06.jpeg",
      "/assets/projects/optical-world-bangalore/optical-world-bangalore-07.jpeg",
      "/assets/projects/optical-world-bangalore/optical-world-bangalore-08.jpeg",
      "/assets/projects/optical-world-bangalore/optical-world-bangalore-09.jpeg",
      "/assets/projects/optical-world-bangalore/optical-world-bangalore-10.jpeg",
      "/assets/projects/optical-world-bangalore/optical-world-bangalore-11.jpeg"
    ],
    "galleryVideos": [
      "/assets/projects/optical-world-bangalore/optical-world-bangalore-video-01.mp4"
    ]
  },
  {
    "slug": "optisch-bangalore",
    "title": "Optisch",
    "location": "Bangalore, Karnataka",
    "coverImage": "/assets/projects/optisch-bangalore/optisch-bangalore-01.jpeg",
    "galleryImages": [
      "/assets/projects/optisch-bangalore/optisch-bangalore-01.jpeg",
      "/assets/projects/optisch-bangalore/optisch-bangalore-02.jpeg",
      "/assets/projects/optisch-bangalore/optisch-bangalore-03.jpeg",
      "/assets/projects/optisch-bangalore/optisch-bangalore-04.jpeg",
      "/assets/projects/optisch-bangalore/optisch-bangalore-05.jpeg",
      "/assets/projects/optisch-bangalore/optisch-bangalore-06.jpeg",
      "/assets/projects/optisch-bangalore/optisch-bangalore-07.jpeg"
    ],
    "galleryVideos": [
      "/assets/projects/optisch-bangalore/optisch-bangalore-video-01.mp4"
    ]
  },
  {
    "slug": "optorium-hyderabad",
    "title": "Optorium",
    "location": "Hyderabad, Telangana",
    "coverImage": "/assets/projects/optorium-hyderabad/optorium-hyderabad-01.png",
    "galleryImages": [
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-01.png",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-02.png",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-03.jpeg",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-04.jpeg",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-05.jpeg",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-06.jpeg",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-07.jpeg",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-08.jpeg",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-09.jpeg",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-10.jpeg",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-11.jpeg",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-12.jpeg",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-13.jpeg",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-14.jpeg",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-15.jpeg",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-16.jpeg",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-17.jpeg",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-18.jpeg",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-19.jpeg",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-20.jpeg",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-21.jpeg",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-22.jpeg",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-23.jpeg",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-24.jpeg",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-25.jpeg"
    ],
    "galleryVideos": [
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-video-01.mp4"
    ]
  },
  {
    "slug": "the-optika-gurgaon",
    "title": "The Optika",
    "location": "Gurugram, Haryana",
    "coverImage": "/assets/projects/the-optika-gurgaon/the-optika-gurgaon-01.jpeg",
    "galleryImages": [
      "/assets/projects/the-optika-gurgaon/the-optika-gurgaon-01.jpeg",
      "/assets/projects/the-optika-gurgaon/the-optika-gurgaon-02.jpeg",
      "/assets/projects/the-optika-gurgaon/the-optika-gurgaon-03.jpeg",
      "/assets/projects/the-optika-gurgaon/the-optika-gurgaon-04.jpeg",
      "/assets/projects/the-optika-gurgaon/the-optika-gurgaon-05.jpeg",
      "/assets/projects/the-optika-gurgaon/the-optika-gurgaon-06.jpeg"
    ],
    "galleryVideos": []
  }
];
