// Auto-generated by scripts/prepare-service-assets.mjs — do not edit manually

export type GeneratedServiceProject = {
  serviceSlug: string;
  slug: string;
  title: string;
  location?: string;
  coverImage: string;
  galleryImages: string[];
  galleryVideos: string[];
};

export type GeneratedServiceGallery = {
  serviceSlug: string;
  coverImage: string;
  galleryImages: string[];
};

export type GeneratedService = {
  slug: string;
  title: string;
  coverImage: string;
  projectCount: number;
  galleryCount: number;
};

export const SERVICES: GeneratedService[] = [
  {
    "slug": "eyewear-optical-retail",
    "title": "Eyewear & Optical Retail",
    "coverImage": "/assets/projects/nagpal-opticians-rudarpur/nagpal-opticians-rudarpur-01.png",
    "projectCount": 6,
    "galleryCount": 0
  },
  {
    "slug": "luxury-jewellery",
    "title": "Luxury Jewellery",
    "coverImage": "/assets/projects/giva/giva-01.jpeg",
    "projectCount": 3,
    "galleryCount": 0
  },
  {
    "slug": "footwear-stores",
    "title": "Footwear Stores",
    "coverImage": "/assets/projects/aretto-shoe/aretto-shoe-01.jpg",
    "projectCount": 2,
    "galleryCount": 0
  },
  {
    "slug": "mobile-electronics",
    "title": "Mobile & Electronics",
    "coverImage": "/assets/projects/cashify/cashify-01.jpeg",
    "projectCount": 1,
    "galleryCount": 0
  },
  {
    "slug": "fashion-apparel",
    "title": "Fashion & Apparel",
    "coverImage": "/assets/projects/killer/killer-01.jpeg",
    "projectCount": 5,
    "galleryCount": 0
  },
  {
    "slug": "gift-toy-stores",
    "title": "Gift & Toy Stores",
    "coverImage": "/assets/galleries/gift-toy-stores/gift-toy-stores-01.jpeg",
    "projectCount": 0,
    "galleryCount": 6
  },
  {
    "slug": "beauty-cosmetics",
    "title": "Beauty & Cosmetics",
    "coverImage": "/assets/galleries/beauty-cosmetics/beauty-cosmetics-01.jpg",
    "projectCount": 0,
    "galleryCount": 7
  },
  {
    "slug": "watch-lifestyle",
    "title": "Watch & Lifestyle",
    "coverImage": "/assets/projects/world-of-watch/world-of-watch-01.jpeg",
    "projectCount": 1,
    "galleryCount": 0
  }
];

export const SERVICE_PROJECTS: GeneratedServiceProject[] = [
  {
    "serviceSlug": "eyewear-optical-retail",
    "slug": "nagpal-opticians-rudarpur",
    "title": "Nagpal Opticians",
    "location": "Rudarpur",
    "coverImage": "/assets/projects/nagpal-opticians-rudarpur/nagpal-opticians-rudarpur-01.png",
    "galleryImages": [
      "/assets/projects/nagpal-opticians-rudarpur/nagpal-opticians-rudarpur-01.png",
      "/assets/projects/nagpal-opticians-rudarpur/nagpal-opticians-rudarpur-02.jpeg",
      "/assets/projects/nagpal-opticians-rudarpur/nagpal-opticians-rudarpur-03.jpeg",
      "/assets/projects/nagpal-opticians-rudarpur/nagpal-opticians-rudarpur-04.jpeg",
      "/assets/projects/nagpal-opticians-rudarpur/nagpal-opticians-rudarpur-05.jpeg",
      "/assets/projects/nagpal-opticians-rudarpur/nagpal-opticians-rudarpur-06.jpeg",
      "/assets/projects/nagpal-opticians-rudarpur/nagpal-opticians-rudarpur-07.jpeg",
      "/assets/projects/nagpal-opticians-rudarpur/nagpal-opticians-rudarpur-08.jpeg",
      "/assets/projects/nagpal-opticians-rudarpur/nagpal-opticians-rudarpur-09.jpeg"
    ],
    "galleryVideos": []
  },
  {
    "serviceSlug": "eyewear-optical-retail",
    "slug": "nethra-opticals-visakhapatnam",
    "title": "Nethra Opticals",
    "location": "Visakhapatnam",
    "coverImage": "/assets/projects/nethra-opticals-visakhapatnam/nethra-opticals-visakhapatnam-01.jpeg",
    "galleryImages": [
      "/assets/projects/nethra-opticals-visakhapatnam/nethra-opticals-visakhapatnam-01.jpeg",
      "/assets/projects/nethra-opticals-visakhapatnam/nethra-opticals-visakhapatnam-02.jpeg",
      "/assets/projects/nethra-opticals-visakhapatnam/nethra-opticals-visakhapatnam-03.jpeg",
      "/assets/projects/nethra-opticals-visakhapatnam/nethra-opticals-visakhapatnam-04.jpeg",
      "/assets/projects/nethra-opticals-visakhapatnam/nethra-opticals-visakhapatnam-05.jpeg"
    ],
    "galleryVideos": []
  },
  {
    "serviceSlug": "eyewear-optical-retail",
    "slug": "optical-world-bangalore",
    "title": "Optical World",
    "location": "Bangalore",
    "coverImage": "/assets/projects/optical-world-bangalore/optical-world-bangalore-01.jpeg",
    "galleryImages": [
      "/assets/projects/optical-world-bangalore/optical-world-bangalore-01.jpeg",
      "/assets/projects/optical-world-bangalore/optical-world-bangalore-02.jpeg",
      "/assets/projects/optical-world-bangalore/optical-world-bangalore-03.jpeg",
      "/assets/projects/optical-world-bangalore/optical-world-bangalore-04.jpeg",
      "/assets/projects/optical-world-bangalore/optical-world-bangalore-05.jpeg",
      "/assets/projects/optical-world-bangalore/optical-world-bangalore-06.jpeg"
    ],
    "galleryVideos": []
  },
  {
    "serviceSlug": "eyewear-optical-retail",
    "slug": "optisch-bangalore",
    "title": "Optisch",
    "location": "Bangalore",
    "coverImage": "/assets/projects/optisch-bangalore/optisch-bangalore-01.jpeg",
    "galleryImages": [
      "/assets/projects/optisch-bangalore/optisch-bangalore-01.jpeg",
      "/assets/projects/optisch-bangalore/optisch-bangalore-02.jpeg",
      "/assets/projects/optisch-bangalore/optisch-bangalore-03.jpeg",
      "/assets/projects/optisch-bangalore/optisch-bangalore-04.jpeg"
    ],
    "galleryVideos": []
  },
  {
    "serviceSlug": "eyewear-optical-retail",
    "slug": "optorium-hyderabad",
    "title": "Optorium",
    "location": "Hyderabad",
    "coverImage": "/assets/projects/optorium-hyderabad/optorium-hyderabad-01.png",
    "galleryImages": [
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-01.png",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-02.jpeg",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-03.jpeg",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-04.jpeg",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-05.jpeg",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-06.jpeg",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-07.jpeg",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-08.jpeg",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-09.jpeg",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-10.jpeg",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-11.jpeg",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-12.jpeg",
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-13.jpeg"
    ],
    "galleryVideos": [
      "/assets/projects/optorium-hyderabad/optorium-hyderabad-video-01.mp4"
    ]
  },
  {
    "serviceSlug": "eyewear-optical-retail",
    "slug": "the-optika-gurgaon",
    "title": "The Optika",
    "location": "Gurgaon",
    "coverImage": "/assets/projects/the-optika-gurgaon/the-optika-gurgaon-01.jpeg",
    "galleryImages": [
      "/assets/projects/the-optika-gurgaon/the-optika-gurgaon-01.jpeg",
      "/assets/projects/the-optika-gurgaon/the-optika-gurgaon-02.jpeg",
      "/assets/projects/the-optika-gurgaon/the-optika-gurgaon-03.jpeg",
      "/assets/projects/the-optika-gurgaon/the-optika-gurgaon-04.jpeg"
    ],
    "galleryVideos": []
  },
  {
    "serviceSlug": "luxury-jewellery",
    "slug": "giva",
    "title": "Giva",
    "coverImage": "/assets/projects/giva/giva-01.jpeg",
    "galleryImages": [
      "/assets/projects/giva/giva-01.jpeg",
      "/assets/projects/giva/giva-02.jpeg",
      "/assets/projects/giva/giva-03.jpeg",
      "/assets/projects/giva/giva-04.jpeg"
    ],
    "galleryVideos": []
  },
  {
    "serviceSlug": "luxury-jewellery",
    "slug": "the-silver-studio",
    "title": "The Silver Studio",
    "coverImage": "/assets/projects/the-silver-studio/the-silver-studio-01.jpeg",
    "galleryImages": [
      "/assets/projects/the-silver-studio/the-silver-studio-01.jpeg",
      "/assets/projects/the-silver-studio/the-silver-studio-02.jpeg",
      "/assets/projects/the-silver-studio/the-silver-studio-03.jpeg"
    ],
    "galleryVideos": []
  },
  {
    "serviceSlug": "luxury-jewellery",
    "slug": "tilakdhari-jewellers",
    "title": "Tilakdhari Jewellers",
    "coverImage": "/assets/projects/tilakdhari-jewellers/tilakdhari-jewellers-01.jpeg",
    "galleryImages": [
      "/assets/projects/tilakdhari-jewellers/tilakdhari-jewellers-01.jpeg",
      "/assets/projects/tilakdhari-jewellers/tilakdhari-jewellers-02.jpeg",
      "/assets/projects/tilakdhari-jewellers/tilakdhari-jewellers-03.jpeg"
    ],
    "galleryVideos": []
  },
  {
    "serviceSlug": "footwear-stores",
    "slug": "aretto-shoe",
    "title": "Aretto Shoe",
    "coverImage": "/assets/projects/aretto-shoe/aretto-shoe-01.jpg",
    "galleryImages": [
      "/assets/projects/aretto-shoe/aretto-shoe-01.jpg",
      "/assets/projects/aretto-shoe/aretto-shoe-02.jpg",
      "/assets/projects/aretto-shoe/aretto-shoe-03.jpg"
    ],
    "galleryVideos": []
  },
  {
    "serviceSlug": "footwear-stores",
    "slug": "id",
    "title": "ID",
    "coverImage": "/assets/projects/id/id-01.jpeg",
    "galleryImages": [
      "/assets/projects/id/id-01.jpeg",
      "/assets/projects/id/id-02.jpeg",
      "/assets/projects/id/id-03.jpeg",
      "/assets/projects/id/id-04.jpeg",
      "/assets/projects/id/id-05.jpeg"
    ],
    "galleryVideos": []
  },
  {
    "serviceSlug": "mobile-electronics",
    "slug": "cashify",
    "title": "Cashify",
    "coverImage": "/assets/projects/cashify/cashify-01.jpeg",
    "galleryImages": [
      "/assets/projects/cashify/cashify-01.jpeg",
      "/assets/projects/cashify/cashify-02.jpeg",
      "/assets/projects/cashify/cashify-03.jpeg",
      "/assets/projects/cashify/cashify-04.jpeg",
      "/assets/projects/cashify/cashify-05.jpeg",
      "/assets/projects/cashify/cashify-06.jpeg"
    ],
    "galleryVideos": []
  },
  {
    "serviceSlug": "fashion-apparel",
    "slug": "killer",
    "title": "Killer",
    "coverImage": "/assets/projects/killer/killer-01.jpeg",
    "galleryImages": [
      "/assets/projects/killer/killer-01.jpeg",
      "/assets/projects/killer/killer-02.jpeg",
      "/assets/projects/killer/killer-03.jpeg"
    ],
    "galleryVideos": []
  },
  {
    "serviceSlug": "fashion-apparel",
    "slug": "nasher-miles",
    "title": "Nasher Miles",
    "coverImage": "/assets/projects/nasher-miles/nasher-miles-01.jpeg",
    "galleryImages": [
      "/assets/projects/nasher-miles/nasher-miles-01.jpeg",
      "/assets/projects/nasher-miles/nasher-miles-02.jpeg",
      "/assets/projects/nasher-miles/nasher-miles-03.jpeg",
      "/assets/projects/nasher-miles/nasher-miles-04.jpeg",
      "/assets/projects/nasher-miles/nasher-miles-05.jpeg",
      "/assets/projects/nasher-miles/nasher-miles-06.jpeg"
    ],
    "galleryVideos": []
  },
  {
    "serviceSlug": "fashion-apparel",
    "slug": "pepe",
    "title": "Pepe",
    "coverImage": "/assets/projects/pepe/pepe-01.jpeg",
    "galleryImages": [
      "/assets/projects/pepe/pepe-01.jpeg",
      "/assets/projects/pepe/pepe-02.jpeg",
      "/assets/projects/pepe/pepe-03.jpeg",
      "/assets/projects/pepe/pepe-04.jpeg",
      "/assets/projects/pepe/pepe-05.jpeg"
    ],
    "galleryVideos": []
  },
  {
    "serviceSlug": "fashion-apparel",
    "slug": "the-bear-house",
    "title": "The Bear House",
    "coverImage": "/assets/projects/the-bear-house/the-bear-house-01.webp",
    "galleryImages": [
      "/assets/projects/the-bear-house/the-bear-house-01.webp",
      "/assets/projects/the-bear-house/the-bear-house-02.jpg",
      "/assets/projects/the-bear-house/the-bear-house-03.jpg"
    ],
    "galleryVideos": []
  },
  {
    "serviceSlug": "fashion-apparel",
    "slug": "zouk",
    "title": "Zouk",
    "coverImage": "/assets/projects/zouk/zouk-01.jpeg",
    "galleryImages": [
      "/assets/projects/zouk/zouk-01.jpeg"
    ],
    "galleryVideos": []
  },
  {
    "serviceSlug": "watch-lifestyle",
    "slug": "world-of-watch",
    "title": "World Of Watch",
    "coverImage": "/assets/projects/world-of-watch/world-of-watch-01.jpeg",
    "galleryImages": [
      "/assets/projects/world-of-watch/world-of-watch-01.jpeg",
      "/assets/projects/world-of-watch/world-of-watch-02.jpeg",
      "/assets/projects/world-of-watch/world-of-watch-03.jpeg"
    ],
    "galleryVideos": [
      "/assets/projects/world-of-watch/world-of-watch-video-01.mp4"
    ]
  }
];

export const SERVICE_GALLERIES: GeneratedServiceGallery[] = [
  {
    "serviceSlug": "gift-toy-stores",
    "coverImage": "/assets/galleries/gift-toy-stores/gift-toy-stores-01.jpeg",
    "galleryImages": [
      "/assets/galleries/gift-toy-stores/gift-toy-stores-01.jpeg",
      "/assets/galleries/gift-toy-stores/gift-toy-stores-02.jpeg",
      "/assets/galleries/gift-toy-stores/gift-toy-stores-03.jpeg",
      "/assets/galleries/gift-toy-stores/gift-toy-stores-04.jpeg",
      "/assets/galleries/gift-toy-stores/gift-toy-stores-05.jpeg",
      "/assets/galleries/gift-toy-stores/gift-toy-stores-06.png"
    ]
  },
  {
    "serviceSlug": "beauty-cosmetics",
    "coverImage": "/assets/galleries/beauty-cosmetics/beauty-cosmetics-01.jpg",
    "galleryImages": [
      "/assets/galleries/beauty-cosmetics/beauty-cosmetics-01.jpg",
      "/assets/galleries/beauty-cosmetics/beauty-cosmetics-02.jpg",
      "/assets/galleries/beauty-cosmetics/beauty-cosmetics-03.jpg",
      "/assets/galleries/beauty-cosmetics/beauty-cosmetics-04.jpg",
      "/assets/galleries/beauty-cosmetics/beauty-cosmetics-05.jpg",
      "/assets/galleries/beauty-cosmetics/beauty-cosmetics-06.jpg",
      "/assets/galleries/beauty-cosmetics/beauty-cosmetics-07.jpg"
    ]
  }
];

export function getProjectsForService(serviceSlug: string): GeneratedServiceProject[] {
  return SERVICE_PROJECTS.filter((p) => p.serviceSlug === serviceSlug);
}

export function getGalleryForService(serviceSlug: string): GeneratedServiceGallery | undefined {
  return SERVICE_GALLERIES.find((g) => g.serviceSlug === serviceSlug);
}
